import {volumes,topics,passages,people,creeds} from './data.js';
import {escapeHTML as h,normalize,searchPassages,searchTopics,emptyState,validateState,newNote,noteMarkdown} from './core.js';
const KEY='bavinck-study-v1';
let state=emptyState(), storageFailed=false, activeNote=null;
try {const raw=localStorage.getItem(KEY); if(raw) state=validateState(JSON.parse(raw));} catch {storageFailed=true;}
const app=document.querySelector('#app');
let indexType='주제',initial='',searchQuery='';
const nav=[['home','⌂','연구 홈'],['bible','▤','성경 탐색'],['books','▥','개혁교의학'],['index','⌕','통합 색인'],['map','◇','교리 지도'],['notes','✎','내 연구'],['bookmarks','☆','북마크']];
function toast(s){document.querySelector('#status').textContent=s;document.querySelector('#status').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>document.querySelector('#status').classList.remove('visible'),3500);}
function persist(){if(storageFailed){toast('기존 저장 자료를 읽지 못했습니다. 백업을 복원하거나 현재 작업을 내려받아 주세요.');return false;}try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{toast('저장 공간에 기록하지 못했습니다. 백업 파일을 내려받아 주세요.');return false;}}
function go(path){location.hash=path;}
function route(){let parts;try{parts=decodeURIComponent(location.hash.slice(1)).split('/');}catch{parts=['home'];}return parts;}
const badge=()=>'<span class="badge">편집 예시 · 원문 미검증</span>';
const topicLink=t=>`<a class="chip" href="#topic/${encodeURIComponent(t)}">${h(t)}</a>`;
function header(eyebrow,title,sub=''){return `<div class="page-heading"><div class="eyebrow">${eyebrow}</div><h1>${h(title)}</h1>${sub?`<p>${h(sub)}</p>`:''}</div>`;}
function cards(list){return list.map(t=>`<article class="resource"><div class="row between"><span class="small">개혁교의학 · 제${t.volume}권 / 탐색 후보</span><button class="icon-button" data-bookmark="${h(t.id)}" aria-label="${h(t.id)} 북마크" aria-pressed="${state.bookmarks.includes(t.id)}">${state.bookmarks.includes(t.id)?'★':'☆'}</button></div><h3><a href="#topic/${encodeURIComponent(t.id)}">${h(t.id)} <span class="en">${t.en}</span></a></h3><p>${h(t.summary)}</p>${badge()}<div class="row actions"><a href="#topic/${encodeURIComponent(t.id)}">확인할 주제 보기 ↗</a><button class="text-button" data-add="${h(t.id)}">＋ 노트에 추가</button></div></article>`).join('');}
function searchForm(value='',id='search'){return `<form id="${id}" class="search"><label class="sr-only" for="query-${id}">성경 본문, 교리, 인물 검색</label><span aria-hidden="true">⌕</span><input id="query-${id}" name="query" value="${h(value)}" placeholder="성경 본문 또는 교리를 입력하세요" required maxlength="120"><button class="primary" type="submit">연구 시작 <span aria-hidden="true">↗</span></button></form>`;}
function home(){return `<section class="hero"><div class="eyebrow">BAVINCK STUDY DESK</div><h1>성경 본문에서,<br><em>깊이 있는 신학으로.</em></h1><p>말씀을 살피고, 교리를 연결하고, 나의 연구로 남기세요.</p>${searchForm()}<div class="examples">시작해 보기 <button data-query="히브리서 12:1–2">히브리서 12:1–2</button><button data-query="로마서 8:28–30">로마서 8:28–30</button><button data-query="언약">언약</button></div><div class="hero-line">SCRIPTURE <span>—</span> DOCTRINE <span>—</span> STUDY</div></section><section><div class="section-head"><h2>이어서 연구하기</h2><a href="#notes">내 연구 전체 ↗</a></div>${state.recent.length?`<div class="recent-grid">${state.recent.map(id=>{const p=passages.find(p=>p.id===id);return `<a class="recent" href="#study/${id}"><span class="small">최근 열어본 본문</span><h3>${p.ref}</h3><p>${p.topics.join(' · ')}</p><span>연구 이어가기 →</span></a>`;}).join('')}</div>`:'<div class="empty compact">아직 연구 기록이 없습니다. 위의 본문으로 첫 연구를 시작해 보세요.</div>'}</section><section><div class="section-head"><h2>개혁교의학 서가</h2><a href="#books">네 권 살펴보기 ↗</a></div>${bookShelf()}</section><section><h2>주제로 시작하기</h2><div class="chips">${['언약','예정','칭의','성화','교회','섭리','삼위일체'].map(topicLink).join('')}</div></section>`;}
function bookShelf(){return `<div class="books">${volumes.map(v=>`<a class="book book-${v.id}" href="#books/${v.id}"><span class="book-author">HERMAN BAVINCK</span><span class="book-number">0${v.id}</span><strong>${v.title}</strong><span>${v.subtitle}</span><span class="book-footer">개혁교의학 <b>↗</b></span></a>`).join('')}</div>`;}
function books(id){const v=volumes.find(v=>v.id===Number(id));return header('THE LIBRARY',v?`제${v.id}권 · ${v.title}`:'개혁교의학 서가','학습용 주제 분류입니다. 실제 판본의 목차와 페이지는 아직 대조하지 않았습니다.')+(v?`<a href="#books">← 전체 서가</a><p>${v.desc}</p><div class="resource-grid">${cards(v.topics.map(id=>topics.find(t=>t.id===id)))}</div>`:bookShelf());}
function results(q){const ps=searchPassages(q),ts=searchTopics(q),persons=people.filter(p=>normalize(p.name+p.alias).includes(normalize(q))),cs=creeds.filter(p=>normalize(p.name+p.alias).includes(normalize(q)));return header('SEARCH','연구 자료 찾기')+searchForm(q)+`<p class="muted">현재 제공하는 시연 데이터 안에서 검색합니다.</p><section><h2>성경 본문 <span class="count">${ps.length}</span></h2>${ps.length?ps.map(p=>`<a class="list-row" href="#study/${p.id}"><strong>${p.ref}</strong><span>${p.topics.join(' · ')} →</span></a>`).join(''):'<div class="empty compact">연결된 본문 예시가 없습니다. <button data-new="'+h(q)+'">이 내용으로 연구 노트 시작</button></div>'}</section><section><h2>교리 <span class="count">${ts.length}</span></h2><div class="resource-grid">${cards(ts)}</div>${!ts.length?'<p class="muted">일치하는 교리가 없습니다.</p>':''}</section>${persons.length?entityList('인물',persons):''}${cs.length?entityList('신조',cs):''}`;}
function study(id){const p=passages.find(p=>p.id===id);if(!p)return missing();return header('SCRIPTURE STUDY',p.ref,'본문을 먼저 살피고, 관련 교리를 연구 노트로 연결하세요.')+`<div class="row study-actions"><button class="primary" data-new="${p.ref}">✎ 설교·성경공부 노트 작성</button><a href="#bible">다른 본문 선택</a></div><div class="study-layout"><div><section class="observation"><div class="eyebrow">01 · 본문 관찰</div><h2>본문에서 출발하기</h2><p class="small">아래는 본문 관찰 예시이며 성경 전문이나 바빙크 인용문이 아닙니다.</p>${p.observations.map(o=>`<p class="observation-item">${h(o)}</p>`).join('')}<p class="muted small">성경 전문은 아직 연결되지 않았습니다. 사용하시는 성경에서 전체 본문을 확인해 주세요.</p></section><section><div class="section-head"><h2>02 · 연결해서 연구할 교리</h2>${badge()}</div><div class="resource-grid">${cards(p.topics.map(t=>topics.find(x=>x.id===t)))}</div></section></div><aside class="context-panel"><div class="eyebrow">RESEARCH COMPANION</div><h3>연구의 길잡이</h3><p>이 연결은 신학적 탐색을 위한 예시입니다. 바빙크가 이 본문을 직접 인용했다는 뜻은 아닙니다.</p><hr><h3>관련 성경 참조</h3>${p.related.map(ref=>`<button class="reference" data-query="${ref}">${ref} ↗</button>`).join('')}<hr><h3>함께 던질 질문</h3><p>본문이 직접 말하는 것은 무엇인가요?</p><p>교리가 이 본문을 이해하는 데 어떤 도움을 주나요?</p><p>책에서 확인한 근거와 나의 적용을 구별했나요?</p></aside></div>`;}
function topic(id){const t=topics.find(t=>t.id===id);if(!t)return missing();return header('DOCTRINE',t.id,t.en)+`<div class="row">${badge()}<button data-bookmark="${t.id}">${state.bookmarks.includes(t.id)?'★ 북마크됨':'☆ 북마크'}</button><button class="primary" data-add="${t.id}">노트에 추가</button></div><section class="observation"><h2>연구 방향</h2><p>${t.summary}</p><p class="muted">이 설명은 앱의 학습용 안내이며, 바빙크의 원문을 요약하거나 인용한 자료가 아닙니다.</p></section><section><h2>책에서 확인하기</h2><div class="resource"><h3>개혁교의학 제${t.volume}권 · 탐색 후보</h3><p>판본 미등록 · 장·절 및 페이지 미확인</p><p class="small">실제 책의 색인에서 ‘${t.id}’을 찾은 뒤 연구 노트에 판본과 페이지를 기록해 주세요.</p><a href="#books/${t.volume}">해당 권 주제 보기 →</a></div></section><section><h2>함께 살펴볼 주제</h2><div class="chips">${t.related.map(topicLink).join('')}</div></section><section><h2>연결된 본문 예시</h2>${passages.filter(p=>p.topics.includes(t.id)).map(p=>`<a class="list-row" href="#study/${p.id}">${p.ref}<span>본문 연구 →</span></a>`).join('')||'<p class="muted">아직 연결된 예시가 없습니다.</p>'}</section>`;}
function bible(){return header('SCRIPTURE INDEX','성경에서 시작하기','현재 다섯 본문에 학습용 교리 연결이 준비되어 있습니다.')+searchForm()+['구약','신약'].map((s,i)=>`<section><h2>${s}</h2>${passages.filter(p=>(p.book==='창세기')===(i===0)).map(p=>`<a class="list-row" href="#study/${p.id}"><strong>${p.ref}</strong><span>${p.topics.join(' · ')} →</span></a>`).join('')}</section>`).join('');}
function entityList(title,items){return `<section><h2>${title}</h2>${items.map(p=>`<article class="resource"><h3>${p.name}</h3>${badge()}<p class="muted small">학습용 연결 · 실제 언급 횟수 및 책 위치 미확인</p><div class="chips">${p.topics.map(topicLink).join('')}</div></article>`).join('')}</section>`;}
function index(){const initials='ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎ',allInitials='ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ';const list=topics.filter(t=>!initial||allInitials[Math.floor((t.id.charCodeAt(0)-44032)/588)]===initial);return header('THE INDEX','통합 색인','교리·본문·인물·신조를 서로 연결하며 탐색하세요.')+`<div class="tabs" role="group" aria-label="색인 종류">${['주제','성경','인물','신조'].map(x=>`<button data-index="${x}" aria-pressed="${indexType===x}" class="${indexType===x?'selected':''}">${x}</button>`).join('')}</div>`+(indexType==='성경'?bible():indexType==='인물'?entityList('인물 색인',people):indexType==='신조'?entityList('신조 색인',creeds):`<div class="alphabet"><button data-initial="" class="${!initial?'selected':''}">전체</button>${[...initials].map(c=>`<button data-initial="${c}" class="${initial===c?'selected':''}">${c}</button>`).join('')}</div>${list.map(t=>`<a class="list-row" href="#topic/${encodeURIComponent(t.id)}"><strong>${t.id}</strong><span>${t.en} ↗</span></a>`).join('')||'<div class="empty">해당 초성의 주제가 아직 없습니다.</div>'}`);}
function map(){return header('DOCTRINE MAP','교리를 연결해서 읽기','노드를 선택하면 연구 방향과 관련 본문을 확인할 수 있습니다.')+`<div class="notice">학습용 탐색 지도입니다. 선은 관련성을 나타내며 시간 순서·인과관계·삼위일체의 위계를 뜻하지 않습니다.</div><div class="map-board"><svg viewBox="0 0 800 430" aria-hidden="true"><path d="M400 70 L130 180 M400 70 L400 180 M400 70 L670 180 M130 180 L130 320 M130 320 L400 320 M400 180 L400 320 M670 180 L670 320 M400 320 L670 320"/></svg><div class="map-nodes">${[['삼위일체','n1'],['창조','n2'],['그리스도','n3'],['언약','n4'],['하나님의 형상','n5'],['속죄','n6'],['교회','n7']].map(([t,c])=>`<a class="map-node ${c}" href="#topic/${encodeURIComponent(t)}">${t}<span>관련 주제 열기 ↗</span></a>`).join('')}</div></div><section><h2>구원의 적용을 함께 연구하기</h2><div class="chips">${['소명','믿음','칭의','성화','견인','영화'].map(topicLink).join('')}</div></section>`;}
function notes(){const list=Object.entries(state.notes).sort((a,b)=>b[1].updated.localeCompare(a[1].updated));return header('MY STUDY','내 연구 노트','이 브라우저에 저장됩니다. 다른 기기로 옮기려면 백업을 사용하세요.')+`<div class="row wrap"><button class="primary" data-new="">＋ 새 연구</button><button id="backup">전체 백업</button><label class="button">백업 복원<input id="restore" type="file" accept="application/json,.json" class="sr-only"></label></div>${storageFailed?'<div class="notice">기존 저장 데이터를 읽지 못하여 자동 저장을 중지했습니다. 기존 데이터는 덮어쓰지 않았습니다.</div>':''}<section>${list.map(([id,n])=>`<a class="list-row" href="#note/${id}"><div><strong>${h(n.title)}</strong><p class="small">${h(n.passage)||'본문 미지정'}</p></div><span>${h(n.updated.slice(0,10))} →</span></a>`).join('')||'<div class="empty">첫 연구를 시작해 보세요.<p>본문 관찰부터 설교 구성까지 한 노트에 정리할 수 있습니다.</p></div>'}</section>`;}
function note(id){const n=state.notes[id];if(!n)return missing();activeNote=id;return header('RESEARCH NOTE','말씀을 나의 연구로', '입력한 내용은 이 브라우저에 자동 저장됩니다.')+`<div class="row wrap"><a href="#notes">← 전체 노트</a><span id="save-state" class="small">${storageFailed?'자동 저장 중지':'저장된 노트'}</span><button id="export-note" data-id="${id}">Markdown 내보내기</button><button class="danger" id="delete-note" data-id="${id}">삭제</button></div><form id="note-form" data-id="${id}" class="note-form"><label>연구 제목<input name="title" value="${h(n.title)}" maxlength="300"></label><label>성경 본문<input name="passage" value="${h(n.passage)}" placeholder="예: 히브리서 12:1–2" maxlength="120"></label>${[['observation','01 · 본문 관찰','문맥, 반복되는 단어, 본문이 직접 말하는 내용을 기록하세요.'],['theology','02 · 교리 연구','책에서 확인한 내용과 나의 신학적 연결을 구별해 기록하세요.'],['application','03 · 적용과 성경공부 질문','우리 공동체에 필요한 적용과 나눔 질문을 적어보세요.'],['outline','04 · 설교 구성','제목, 중심 명제, 대지, 적용과 기도 순서로 정리해 보세요.']].map(([key,title,placeholder])=>`<label>${title}<textarea name="${key}" rows="6" maxlength="200000" placeholder="${placeholder}">${h(n[key])}</textarea></label>`).join('')}<div class="two-col"><label>책 판본<input name="edition" value="${h(n.edition)}" placeholder="출판사 · 번역자 · 출판연도" maxlength="300"></label><label>확인한 페이지<input name="page" value="${h(n.page)}" placeholder="권 · 장 · 페이지" maxlength="300"></label></div></form><section><h2>모아 둔 참고 주제</h2><p class="small muted">모든 연결은 원문 미검증 예시입니다. 책을 확인한 근거를 위에 기록해 주세요.</p><div class="chips">${n.sources.map(t=>`<span class="source-chip">${topicLink(t)}<button data-remove="${t}" data-note="${id}" aria-label="${t} 제거">×</button></span>`).join('')||'<p>교리 카드의 ‘노트에 추가’로 자료를 모으세요.</p>'}</div><a href="#index">색인에서 자료 찾기 →</a></section>`;}
function missing(){return header('NOT FOUND','자료를 찾을 수 없습니다.')+'<a href="#home">연구 홈으로 →</a>';}
function render(){const [page='home',id]=route();let content;switch(page){case 'home':content=home();break;case 'search':searchQuery=id||'';content=results(searchQuery);break;case 'study':content=study(id);break;case 'topic':content=topic(id);break;case 'books':content=books(id);break;case 'bible':content=bible();break;case 'index':content=index();break;case 'map':content=map();break;case 'notes':content=notes();break;case 'note':content=note(id);break;case 'bookmarks':content=header('SAVED REFERENCES','북마크')+(state.bookmarks.length?`<div class="resource-grid">${cards(state.bookmarks.map(id=>topics.find(t=>t.id===id)))}</div>`:'<div class="empty">교리 카드의 별을 눌러 자주 찾는 자료를 모아두세요.</div>');break;default:content=missing();}app.innerHTML=`<aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">B.</span><span>BAVINCK<small>STUDY DESK</small></span></a><div class="nav-caption">나의 신학 연구실</div><nav aria-label="주 메뉴">${nav.map(([key,icon,name])=>`<a href="#${key}" class="${key===page?'active':''}" ${key===page?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${name}</a>`).join('')}</nav><div class="sidebar-bottom"><span class="small">성경 · 교리 · 연구</span><p>연결하며 읽는<br>개혁교의학</p><span class="version">PROTOTYPE 0.1</span></div></aside><div class="workspace"><header class="topbar"><a href="#home" class="mobile-brand">B. BAVINCK</a><span class="breadcrumb">나의 연구실 <span>/</span> ${h(nav.find(x=>x[0]===page)?.[2]||'본문 연구')}</span><a href="#notes">✎ 내 연구 노트</a></header><main id="main" tabindex="-1">${content}</main><footer class="footer">BAVINCK STUDY <span>학습용 예시 데이터 · 책 위치 검증 전 · AI 미연결</span></footer></div><nav class="mobile-nav" aria-label="모바일 메뉴">${nav.filter(x=>['home','bible','index','map','notes'].includes(x[0])).map(([key,icon,name])=>`<a href="#${key}" class="${page===key?'active':''}"><span>${icon}</span>${name.replace('연구 홈','홈').replace('성경 탐색','성경').replace('통합 색인','색인')}</a>`).join('')}</nav>`;}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function startNote(passage){const id=crypto.randomUUID();state.notes[id]=newNote(passage);activeNote=id;persist();go('note/'+id);}
app.addEventListener('submit',e=>{if(e.target.id==='search'){e.preventDefault();const q=new FormData(e.target).get('query').trim();if(q)go('search/'+encodeURIComponent(q));}else e.preventDefault();});
app.addEventListener('click',e=>{const el=e.target.closest('button,[data-query]');if(!el)return;
 if(el.dataset.query!==undefined)go('search/'+encodeURIComponent(el.dataset.query));
 if(el.dataset.new!==undefined)startNote(el.dataset.new);
 if(el.dataset.bookmark){const id=el.dataset.bookmark;state.bookmarks=state.bookmarks.includes(id)?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];persist();render();}
 if(el.dataset.add){if(!activeNote||!state.notes[activeNote]){activeNote=crypto.randomUUID();state.notes[activeNote]=newNote();}const n=state.notes[activeNote];if(!n.sources.includes(el.dataset.add))n.sources.push(el.dataset.add);n.updated=new Date().toISOString();persist();toast('연구 노트에 추가했습니다: '+n.title);}
 if(el.dataset.index){indexType=el.dataset.index;render();}
 if(el.dataset.initial!==undefined){initial=el.dataset.initial;render();}
 if(el.dataset.remove){state.notes[el.dataset.note].sources=state.notes[el.dataset.note].sources.filter(t=>t!==el.dataset.remove);persist();render();}
 if(el.id==='backup')download('bavinck-study-backup.json',JSON.stringify(state,null,2),'application/json');
 if(el.id==='export-note')download('bavinck-study-note.md',noteMarkdown(state.notes[el.dataset.id]),'text/markdown');
 if(el.id==='delete-note'&&confirm('이 연구 노트를 삭제할까요? 삭제 전 내보내기로 보관할 수 있습니다.')){delete state.notes[el.dataset.id];persist();go('notes');}
});
app.addEventListener('input',e=>{const f=e.target.closest('#note-form');if(!f)return;const n=state.notes[f.dataset.id];n[e.target.name]=e.target.value;n.updated=new Date().toISOString();document.querySelector('#save-state').textContent=persist()?'자동 저장됨':'저장 실패 · 내보내기 필요';});
app.addEventListener('change',async e=>{if(e.target.id!=='restore')return;const file=e.target.files[0];if(!file)return;try{if(file.size>5_000_000)throw Error('5MB 이하의 백업 파일을 선택해 주세요.');const restored=validateState(JSON.parse(await file.text()));if(!confirm('백업 내용으로 현재 브라우저의 노트와 북마크를 교체할까요? 먼저 전체 백업을 권합니다.'))return;localStorage.setItem(KEY,JSON.stringify(restored));state=restored;storageFailed=false;activeNote=null;render();toast('백업을 복원했습니다.');}catch(error){toast('복원하지 못했습니다. '+error.message);}});
window.addEventListener('hashchange',()=>{const [page,id]=route();if(page==='study'&&passages.some(p=>p.id===id)){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);persist();}render();window.scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});});
window.addEventListener('storage',e=>{if(e.key===KEY)toast('다른 탭에서 자료가 변경되었습니다. 여러 탭의 동시 편집은 지원하지 않습니다. 작업을 내보낸 뒤 새로고침해 주세요.');});
render();
